image: golang:1.18-buster

stages:
  #  - testing
  - deploy

.install-sam:
  before_script:
    - apt update
    - apt install -y python3-pip
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade

variables:
  CMD_PATH: cmd/imagefilter/

#testing:
#  stage: testing
#  script:
#    - go get -d -v ./...
#    - cd "$CMD_PATH"
#    - go build
#    - go test -v ./...

deploy:
  stage: deploy
  extends: .install-sam
  script:
    - sam build
    - sam package --output-template-file packaged.yaml
    - sam deploy --template-file packaged.yaml --no-fail-on-empty-changeset --parameter-overrides "SMSReceiver=\"$SMS_RECEIVER\" DomainName=\"$DOMAIN_NAME\""
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
