image: golang:1.17-buster

stages:
  #  - testing
  - deploy

.install-sam:
  before_script:
    - apt update
    - apt install -y python3-pip
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade

variables:
  CMD_PATH: cmd/imagefilter/

#testing:
#  stage: testing
#  script:
#    - go get -d -v ./...
#    - cd "$CMD_PATH"
#    - go build
#    - go test -v ./...

deploy:
  stage: deploy
  extends: .install-sam
  script:
    - sam build
    - sam deploy --no-fail-on-empty-changeset --paramter_overrides "SMSReceiver=\"$SMS_RECEIVER\""
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
