version = 0.1

[default.package.parameters]
s3_bucket = "safeguard-lambda-artifacts"
region = "eu-central-1"

[default.deploy.parameters]
region = "eu-central-1"
stack_name = "control"
capabilities = "CAPABILITY_IAM"
s3_bucket = "safeguard-lambda-artifacts"